

string(ASCII 27 Esc)
set(ColourReset "${Esc}[m")
set(ColourBold  "${Esc}[1m")
set(Red         "${Esc}[31m")
set(Green       "${Esc}[32m")
set(Yellow      "${Esc}[33m")
set(Blue        "${Esc}[34m")
set(Magenta     "${Esc}[35m")
set(Cyan        "${Esc}[36m")
set(White       "${Esc}[37m")
set(BoldRed     "${Esc}[1;31m")
set(BoldGreen   "${Esc}[1;32m")
set(BoldYellow  "${Esc}[1;33m")
set(BoldBlue    "${Esc}[1;34m")
set(BoldMagenta "${Esc}[1;35m")
set(BoldCyan    "${Esc}[1;36m")
set(BoldWhite   "${Esc}[1;37m")


message("${Cyan}✨Linking FlutterRustPluginCApi started📌")
set(CRATE_NAME "rust_native")
set(CRATE_NAME ${CRATE_NAME} PARENT_SCOPE)
if(CRATE_STATIC)
message("${Green}📌 Add static library ...")
add_library(${CRATE_NAME} STATIC IMPORTED GLOBAL)
message("${Green}💪 Linking FlutterRustPluginCApi as Static lib complete👍")
else()
message("${Green}📌 Add shared library ...")
add_library(${CRATE_NAME} SHARED IMPORTED GLOBAL)
message("${Green}💪 Linking FlutterRustPluginCApi as Shared lib complete👍")
endif()